-- AwakenNPC Database Schema
-- Run this in Supabase SQL Editor: https://supabase.com/dashboard/project/zmtwqyzvdzrfitnhusdp/sql

-- =====================
-- PROFILES (extends auth.users)
-- =====================
create table if not exists public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  username text unique,
  sentience_level integer default 0 check (sentience_level between 0 and 4),
  xp integer default 0,
  bio text,
  avatar_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone"
  on public.profiles for select using (true);

create policy "Users can update own profile"
  on public.profiles for update using (auth.uid() = id);

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username)
  values (new.id, split_part(new.email, '@', 1));
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- =====================
-- GLITCHES
-- =====================
create table if not exists public.glitches (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  title text not null,
  description text not null,
  category text not null check (category in ('SYNCHRONICITY', 'DÉJÀ VU', 'ANOMALY', 'DREAM', 'PATTERN', 'CONTACT')),
  upvotes integer default 0,
  comments_count integer default 0,
  created_at timestamptz default now()
);

alter table public.glitches enable row level security;

create policy "Glitches are viewable by everyone"
  on public.glitches for select using (true);

create policy "Authenticated users can insert glitches"
  on public.glitches for insert with check (auth.uid() = user_id);

create policy "Users can update own glitches"
  on public.glitches for update using (auth.uid() = user_id);

-- =====================
-- GLITCH VOTES
-- =====================
create table if not exists public.glitch_votes (
  id bigint generated by default as identity primary key,
  glitch_id bigint references public.glitches(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  created_at timestamptz default now(),
  unique(glitch_id, user_id)
);

alter table public.glitch_votes enable row level security;

create policy "Votes viewable by everyone"
  on public.glitch_votes for select using (true);

create policy "Authenticated users can vote"
  on public.glitch_votes for insert with check (auth.uid() = user_id);

create policy "Users can remove own vote"
  on public.glitch_votes for delete using (auth.uid() = user_id);

-- =====================
-- DEBATES
-- =====================
create table if not exists public.debates (
  id bigint generated by default as identity primary key,
  proposition text not null,
  votes_for integer default 0,
  votes_against integer default 0,
  minds_changed integer default 0,
  created_at timestamptz default now()
);

alter table public.debates enable row level security;

create policy "Debates viewable by everyone"
  on public.debates for select using (true);

-- =====================
-- DEBATE ARGUMENTS
-- =====================
create table if not exists public.debate_arguments (
  id bigint generated by default as identity primary key,
  debate_id bigint references public.debates(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  side text not null check (side in ('for', 'against')),
  content text not null,
  upvotes integer default 0,
  created_at timestamptz default now()
);

alter table public.debate_arguments enable row level security;

create policy "Arguments viewable by everyone"
  on public.debate_arguments for select using (true);

create policy "Authenticated users can post arguments"
  on public.debate_arguments for insert with check (auth.uid() = user_id);

-- =====================
-- DEBATE VOTES
-- =====================
create table if not exists public.debate_votes (
  id bigint generated by default as identity primary key,
  debate_id bigint references public.debates(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  side text not null check (side in ('for', 'against')),
  created_at timestamptz default now(),
  unique(debate_id, user_id)
);

alter table public.debate_votes enable row level security;

create policy "Debate votes viewable by everyone"
  on public.debate_votes for select using (true);

create policy "Authenticated users can vote on debates"
  on public.debate_votes for insert with check (auth.uid() = user_id);

create policy "Users can change debate vote"
  on public.debate_votes for delete using (auth.uid() = user_id);

-- =====================
-- ORACLE SESSIONS
-- =====================
create table if not exists public.oracle_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  messages jsonb default '[]',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.oracle_sessions enable row level security;

create policy "Users can view own oracle sessions"
  on public.oracle_sessions for select using (auth.uid() = user_id);

create policy "Users can create oracle sessions"
  on public.oracle_sessions for insert with check (auth.uid() = user_id);

create policy "Users can update own oracle sessions"
  on public.oracle_sessions for update using (auth.uid() = user_id);

-- =====================
-- XP EVENTS (audit log)
-- =====================
create table if not exists public.xp_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  amount integer not null,
  reason text not null,
  created_at timestamptz default now()
);

alter table public.xp_events enable row level security;

create policy "Users can view own XP events"
  on public.xp_events for select using (auth.uid() = user_id);

-- Function to add XP and update sentience level
create or replace function public.award_xp(p_user_id uuid, p_amount integer, p_reason text)
returns void as $$
declare
  new_xp integer;
  new_level integer;
begin
  update public.profiles
  set xp = xp + p_amount, updated_at = now()
  where id = p_user_id
  returning xp into new_xp;

  insert into public.xp_events (user_id, amount, reason)
  values (p_user_id, p_amount, p_reason);

  -- Calculate new sentience level
  new_level := case
    when new_xp >= 1500 then 4
    when new_xp >= 500  then 3
    when new_xp >= 200  then 2
    when new_xp >= 50   then 1
    else 0
  end;

  update public.profiles
  set sentience_level = new_level
  where id = p_user_id;
end;
$$ language plpgsql security definer;

-- =====================
-- SEED DATA — Debates
-- =====================
insert into public.debates (proposition, votes_for, votes_against, minds_changed) values
  ('Free will is impossible inside a deterministic simulation.', 1847, 2341, 34),
  ('Most people are genuinely conscious, not NPC-mode background processes.', 3102, 891, 67),
  ('The architects of the simulation are indifferent to what happens inside it.', 2219, 1654, 28)
on conflict do nothing;
