-- Newsletter subscribers
-- Run this in Supabase SQL Editor

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  archetype_id text,
  source text default 'site',
  confirmed boolean default false,
  unsubscribed_at timestamptz,
  created_at timestamptz default now(),
  metadata jsonb default '{}'::jsonb
);

alter table public.subscribers enable row level security;

-- Anyone can insert (public signup), but nobody can read directly
-- Reads go through service-role API only.
create policy "Anyone can subscribe"
  on public.subscribers for insert with check (true);

-- No public select policy — subscribers list is private.
-- Use service_role key from server-side API for admin queries.

create index if not exists subscribers_email_idx on public.subscribers (email);
create index if not exists subscribers_created_at_idx on public.subscribers (created_at desc);
