-- Make Glitches & Debates work without auth
-- Anonymous handles + service-role-driven mutations

-- Add anonymous handle column to glitches (allow user_id null)
alter table public.glitches alter column user_id drop not null;
alter table public.glitches add column if not exists anon_handle text;
alter table public.glitches add column if not exists archetype_id text;

-- Allow anyone to read
drop policy if exists "Glitches are viewable by everyone" on public.glitches;
create policy "Glitches are viewable by everyone"
  on public.glitches for select using (true);

-- Inserts handled via service role API only
drop policy if exists "Authenticated users can insert glitches" on public.glitches;

-- Debates: add seed propositions, allow anon arguments
create table if not exists public.debate_arguments (
  id bigint generated by default as identity primary key,
  debate_id bigint references public.debates(id) on delete cascade,
  side text not null check (side in ('FOR', 'AGAINST')),
  text text not null,
  upvotes integer default 0,
  anon_handle text,
  archetype_id text,
  created_at timestamptz default now()
);
alter table public.debate_arguments enable row level security;
create policy "Arguments viewable by everyone"
  on public.debate_arguments for select using (true);

-- Public read on debates
alter table public.debates enable row level security;
drop policy if exists "Debates are viewable" on public.debates;
create policy "Debates are viewable"
  on public.debates for select using (true);

-- Vote ledger (idempotent via fingerprint)
create table if not exists public.anon_votes (
  id bigint generated by default as identity primary key,
  fingerprint text not null,           -- client-generated UUID stored in localStorage
  target_kind text not null check (target_kind in ('GLITCH', 'DEBATE_ARG', 'DEBATE_SIDE')),
  target_id bigint not null,
  side text,                           -- for debate side votes: 'FOR' / 'AGAINST'
  created_at timestamptz default now(),
  unique (fingerprint, target_kind, target_id, side)
);
alter table public.anon_votes enable row level security;
create policy "Votes viewable" on public.anon_votes for select using (true);

create index if not exists anon_votes_fingerprint_idx
  on public.anon_votes (fingerprint);
create index if not exists anon_votes_target_idx
  on public.anon_votes (target_kind, target_id);
